/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ase.rrts;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class RRTSApp {
    public String getGreeting() {
        return "Road Repair and Tracking System";
    }

    /**
     * Main driver code
     * @param args
     */
    public static void main(String[] args) {
        System.out.println(new RRTSApp().getGreeting());
        SpringApplication.run(RRTSApp.class, args);
    }
}
